services:
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ledger

volumes:
  db_data:
