services:
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ledger
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 30s
      retries: 3


  app:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db


volumes:
  db_data:
