// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type LedgerDirection string

const (
	LedgerDirectionIN  LedgerDirection = "IN"
	LedgerDirectionOUT LedgerDirection = "OUT"
)

func (e *LedgerDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerDirection(s)
	case string:
		*e = LedgerDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerDirection: %T", src)
	}
	return nil
}

type NullLedgerDirection struct {
	LedgerDirection LedgerDirection
	Valid           bool // Valid is true if LedgerDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerDirection) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerDirection), nil
}

type TransactionType string

const (
	TransactionTypePayment    TransactionType = "payment"
	TransactionTypeSettlement TransactionType = "settlement"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType
	Valid           bool // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type Ledger struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	Direction          NullLedgerDirection
	AmountCurrencyCode string
	AmountUnits        int64
	AmountNanos        int32
	TransactionID      pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type Transaction struct {
	ID               pgtype.UUID
	LastUpdatingUser pgtype.UUID
	Type             NullTransactionType
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}
